### PR TITLE
docs: added chapter on design

### PR DESCRIPTION
**Pull request by e8johan**
Changed wording around app manifests
Documented what IPC is
Removed reference to ipfilter :-)

### CODE REVIEW

**Comment by frznlogic** [comment]
Please fix the merge conflict? :)

**Comment by e8johan** [comment]
Will fix the merge conflict and do some linebreaking :-)

**Comment by breakreturn** [comment]
All in all I think this text introduces some nomenclature we are not using currently, and might be slightly confusing as what SC brings compared to what a launcher would bring w.r.t. integration and what's mandated and what's implied patterns etc. But I think that just means we need to revise and iterate as we go along. I am fine with merging this as it is now.

**Review by tobsan — CHANGES_REQUESTED** [review]
Lines are still super long and this request still has merge conflicts. Please fix both things.

**Pull request closed without merging**
