### PR TITLE
lxc: update softwarecontainer to use lxc 3.1.0

### PR DESCRIPTION
**Pull request by TSAnsari**
Signed-off-by: Tariq Ansari <tansari@luxoft.com>

### CODE REVIEW

**Review by fhajredini — APPROVED** [review]

**Comment by fhajredini** [comment]
The version is mentioned here as well. https://github.com/Pelagicore/vagrant-cookbook/blob/master/deps/softwarecontainer-dependencies.sh, does this need to point to master now or is the hard coded version ok?

**Comment by TSAnsari** [comment]
> The version is mentioned here as well. https://github.com/Pelagicore/vagrant-cookbook/blob/master/deps/softwarecontainer-dependencies.sh, does this need to point to master now or is the hard coded version ok?

In the above cookbook link it is fetching and installing from lxc 3.1.0 branch/tag to be used by softwarecontainer. It should point to 3.1.0 tag.

In this commit it only updates CMake so that it checks for the 3.1.0 installed version. The reason being that softwarecontainer was updated to work with 3.1.0 or higher versions.

**Comment by sashko** [comment]
> > The version is mentioned here as well. https://github.com/Pelagicore/vagrant-cookbook/blob/master/deps/softwarecontainer-dependencies.sh, does this need to point to master now or is the hard coded version ok?
> 
> In the above cookbook link it is fetching and installing from lxc 3.1.0 branch/tag to be used by softwarecontainer. It should point to 3.1.0 tag.
> 
> In this commit it only updates CMake so that it checks for the 3.1.0 installed version. The reason being that softwarecontainer was updated to work with 3.1.0 or higher versions.

Would be nice if it was explained in the commit message.

**Comment by martin-ejdestig** [comment]
> In this commit it only updates CMake

The submodule is updated as well... ? I meant to ask if this was by accident or not since it is not mentioned in commit message. Did not though... but this makes it sound like it was by accident...?

**Comment by martin-ejdestig** [comment]
If the submodule was not update by accident, it would have been nice with a blurb about it in the commit message. :)

**Comment by TSAnsari** [comment]
> > > The version is mentioned here as well. https://github.com/Pelagicore/vagrant-cookbook/blob/master/deps/softwarecontainer-dependencies.sh, does this need to point to master now or is the hard coded version ok?
> > 
> > 
> > In the above cookbook link it is fetching and installing from lxc 3.1.0 branch/tag to be used by softwarecontainer. It should point to 3.1.0 tag.
> > In this commit it only updates CMake so that it checks for the 3.1.0 installed version. The reason being that softwarecontainer was updated to work with 3.1.0 or higher versions.
> 
> Would be nice if it was explained in the commit message.

Sure will add more comment

**Comment by TSAnsari** [comment]
> > In this commit it only updates CMake
> 
> The submodule is updated as well... ? I meant to ask if this was by accident or not since it is not mentioned in commit message. Did not though... but this makes it sound like it was by accident...?

Not an accident :) Will add more comment

**Comment by TSAnsari** [comment]
Updated the commit message

**Pull request merged**
