### PR TITLE
adds initial CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by tobsan**
Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

### CODE REVIEW

**Comment by tobsan** [comment]
I'd love some comments on this.

**Comment by DunderRoffe** [comment]
Maybe we should add why we do this and that it is a temporary solution.

**Comment by jeremiah** [comment]
I think this matches the vision we had in our internal discussions. I think the implementation is great, my only reservation is the language of the document but that we can iterate on.

**Comment by jeremiah** [comment]
(previous comments were for something else.) 

@DunderRoffe I agree -- we should note that this is just a temporary solution.

**Review by breakreturn — APPROVED** [review]

**Review by jeremiah — APPROVED** [review]
Looks good. :+1:

**Pull request merged**
