### PR TITLE
contributing.md: wording updates + various

### PR DESCRIPTION
**Pull request by tobsan**
Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

### CODE REVIEW

**Comment by rpannek** [comment]
Is the tag supposed to be a list of all the filenames of the changed files? I think we need to rethink the whole tag thing in the headline, I'm not sure we even need to force us to use it in cases like this one.

**Comment by tobsan** [comment]
@rpannek no, the tag can be anything, but in this case the change only applies to one file, so it is reasonable to say that imho. In general the tag is supposed to mark what part of the code base was changed (if one chooses to use a tag, it is optional), like "agent: blablabla" or "common: blablabla" or even "dbusgateway: blablabla"

**Comment by rpannek** [comment]
Your other examples sound reasonable, but I personally really dislike putting the name of the file there (especially with the suffix).

**Comment by tobsan** [comment]
Updated the PR after comments from @jeremiah

**Review by rpannek — APPROVED** [review]

**Pull request merged**
